#!/usr/bin/env bash

set -e

# Check script is being executed appropriatly
if [[ -z "${BASH_SOURCE}" ]]; then
    msg="This file should be executed directly with \`./install\`
    and not interpreted with \`sh ./install\`"
    echo "$msg"
    exit 1
fi

# Constants
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="dotbot/core"
DOTBOT_BIN="bin/dotbot"
PROFILE_DIR="profiles"
DEFAULT_PROFILE="base"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "dotbot/asdf"
git submodule update --init --recursive "dotbot/brewfile"
git submodule update --init --recursive "dotbot/vscode"

# Scripts will setup PATH appropriatly
# but need to assume first run so make sure
# everything we need is there
export PATH="/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:$PATH"

for profile in ${DEFAULT_PROFILE} ${@}; do
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -v -d "${BASEDIR}" \
        --plugin-dir dotbot/asdf \
        --plugin-dir dotbot/brewfile \
        --plugin-dir dotbot/vscode \
        -c "${PROFILE_DIR}/${profile}.yaml"
done
