- defaults:
    link:
        relink: true
        create: true

- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.vimrc: configs/vim/.vimrc
    ~/.hushlogin: configs/.hushlogin
    ~/.ssh/config: configs/ssh/config
    ~/.ssh/authorized_keys: configs/ssh/authorized_keys
    ~/.config/fish/conf.d: configs/fish/conf.d
    ~/.config/fish/fisher/fishfile: configs/fish/fisher/fishfile
    ~/.config/fish/functions: configs/fish/functions
    ~/.config/flake8: configs/python/flake8
    ~/.switch-display/config.toml: configs/switch-display/config.toml
    ~/.gitconfig: configs/git/.gitconfig

- shell:
    -
        command: ./scripts/homebrew
        description: Installing Homebrew
        stdin: true
        stdout: true
        stderr: true
    - grep -qxF "$HOMEBREW_BIN/fish" /etc/shells || echo "$HOMEBREW_BIN/fish" | sudo tee -a /etc/shells
    - chsh -s $HOMEBREW_BIN/fish

- brewfile:
    file: configs/brew/Brewfile.base
    stdout: true
    stderr: true
    include: ['tap', 'brew', 'cask', 'mas']

- asdf:
    - plugin: cmake
      url: https://github.com/srivathsanmurali/asdf-cmake.git
    - plugin: golang
      url: https://github.com/kennyp/asdf-golang.git
    - plugin: python
      url: https://github.com/danhper/asdf-python.git
    - plugin: ruby
      url: https://github.com/asdf-vm/asdf-ruby.git
    - plugin: rust
      url: https://github.com/code-lever/asdf-rust.git
    - plugin: nodejs
      url: https://github.com/asdf-vm/asdf-nodejs.git

- shell:
    -
      command: bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
      description: Add nodejs cert to keychain
      stdin: true
      stdout: true
      stderr: true

- shell:
    -
        command: ./scripts/pipx ./configs/pipx/Pipxfile.base
        description: Installing Pipxfile
        stdin: true
        stdout: true
        stderr: true
